---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: false
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
- name: url
  type: text
  config:
    required: false
  label: URL
  description: The project's URL.
pages:
- projects/campaign-against-gambling-ads.md
- projects/clean-up-gambling.md
- projects/gamlearn.md
- projects/instantcard.md
- projects/labour-party-graphic-designers.md
- projects/nbt-guidelines.md
- projects/tackling-gambling-stigma.md
- projects/vita-ca.md
